name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v23
      - uses: DeterminateSystems/magic-nix-cache-action@v15

      - run: nix flake check
      - run: nix develop -c treefmt --ci
      - run: nix develop -c gleam build --warnings-as-errors
      - run: nix develop -c gleam test

  shipment:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v23
      - uses: DeterminateSystems/magic-nix-cache-action@v15
      - run: nix develop -c gleam export erlang-shipment
      - uses: actions/upload-artifact@v4
        with:
          name: erlang-shipment
          path: build/erlang-shipment
          if-no-files-found: error
          retention-days: 14
